name: ubuntu-accomplishments
base: core18
version: '0.2'
icon: desktop/ubuntu-accomplishments.svg
summary: Ubuntu Accomplishments
description: |
  The Ubuntu Accomplishments system provides a simple, cohesive way to browse
  different opportunities in the Ubuntu community and beyond, find out how to
  participate and accomplish them, and see different accomplishments in one
  place.
grade: stable
confinement: strict
compression: lzo

parts:
  daemon:
    plugin: nil
    source: https://github.com/UbuntuAccomplishments/daemon.git
    override-build: |
      dart pub get
      dart run build_runner build --delete-conflicting-outputs
      dart compile exe --output accomplishments-daemon bin/accom_daemon.dart
      install -m755 -D -t $SNAPCRAFT_PART_INSTALL/bin accomplishments-daemon
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/usr/share/accomplishments/daemon/data data/ubuntu-accomplishments-system.svg
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/usr/share/accomplishments/daemon data/daemon/validation-key.pub
    stage-packages:
      - klibc-utils
      - python3
      - python3-launchpadlib # for community-accomplishments
      - python3-requests # for community-accomplishments

  viewer:
    plugin: flutter
    source: https://github.com/UbuntuAccomplishments/viewer.git
    build-packages: [rsync]
    override-build: |
      flutter pub get
      flutter pub run build_runner build --delete-conflicting-outputs
      snapcraftctl build

  desktop:
    plugin: dump
    source: desktop
    organize:
      accomplishments-viewer.sh: bin/accomplishments-viewer.sh
      ubuntu-accomplishments.desktop: usr/share/applications/ubuntu-accomplishments.desktop
      ubuntu-accomplishments.svg: usr/share/icons/ubuntu-accomplishments.svg

  community-accomplishments:
    plugin: nil
    source: https://github.com/UbuntuAccomplishments/community-accomplishments.git
    override-build: |
      ./install.sh $SNAPCRAFT_PART_INSTALL/usr/share/accomplishments
  
  desktop-accomplishments:
    plugin: nil
    source: https://github.com/UbuntuAccomplishments/desktop-accomplishments.git
    override-build: |
      ./install.sh $SNAPCRAFT_PART_INSTALL/usr/share/accomplishments
    stage:
      # these still need porting or removing entirely
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/accessories/accomplishments-shared-with-validation-server.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/gaming/gnomine*.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/gaming/mahjongg*.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/gaming/sudoku*.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/general/installed-on-nexus7.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/multimedia/importshotwell.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/multimedia/multimedia-added-music.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/multimedia/multimedia-added-photos.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/multimedia/musicinrhythmbox.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/networking/gwibber-*.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/productivity/libreoffice-create-document.accomplishment

slots:
  accomplishments-service:
    interface: dbus
    bus: session
    name: org.ubuntu.Accomplishments

plugs:
  accomplishments-viewer:
    interface: dbus
    bus: session
    name: org.ubuntu.Accomplishments
  etc-lsb-release:
    interface: system-files
    read:
      - /etc/lsb-release
  # gnomine-scores:
  #   interface: personal-files
  #   read:
  #     - $HOME/.local/share/gnome-mines/scores
  # mahjongg-scores:
  #   interface: system-files
  #   read:
  #     - $HOME/.local/share/gnome-mahjongg/history
  # sudoku-scores:
  #   interface: personal-files
  #   read:
  #     - $HOME/.local/share/gnome-sudoku/finished
  # missing rythmbox plug
  # missing shotwell plug

apps:
  daemon:
    command: bin/accomplishments-daemon
    extensions: [flutter-beta]
    daemon: simple
    passthrough:
      daemon-scope: user
    slots:
      - accomplishments-service # the dbus service
    plugs:
      - gsettings
      - hardware-observe
      - home
      - log-observe
      - network
      # our custom system access below:
      # - gnomine-scores
      # - mahjongg-scores
      # - sudoku-scores
      - etc-lsb-release

  ubuntu-accomplishments:
    extensions: [flutter-beta]
    command: bin/accomplishments-viewer.sh
    common-id: org.ubuntu.Accomplishments
    desktop: usr/share/applications/ubuntu-accomplishments.desktop
    plugs:
      - accomplishments-viewer # the dbus service
