name: ubuntu-accomplishments
base: core22
version: '0.2'
summary: Ubuntu Accomplishments
description: |
  The Ubuntu Accomplishments system provides a simple, cohesive way to browse
  different opportunities in the Ubuntu community and beyond, find out how to
  participate and accomplish them, and see different accomplishments in one
  place.
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $CRAFT_PART_INSTALL/usr/bin/dart
      export PATH="$CRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
      flutter channel stable
      flutter upgrade
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''

  daemon:
    after: [flutter-git]
    plugin: nil
    source: https://github.com/UbuntuAccomplishments/daemon.git
    override-build: |
      set -eux
      dart pub get
      dart run build_runner build --delete-conflicting-outputs
      dart compile exe --output accomplishments-daemon bin/accom_daemon.dart
      install -m755 -D -t $SNAPCRAFT_PART_INSTALL/bin accomplishments-daemon
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/usr/share/accomplishments/daemon/data data/ubuntu-accomplishments-system.svg
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/usr/share/accomplishments/daemon data/daemon/validation-key.pub
    stage-packages:
      - klibc-utils
      - python3
      - python3-launchpadlib # for community-accomplishments
      - python3-requests # for community-accomplishments

  viewer:
    after: [flutter-git]
    plugin: nil
    source: https://github.com/UbuntuAccomplishments/viewer.git
    override-build: |
      set -eux
      flutter pub get
      flutter pub run build_runner build --delete-conflicting-outputs
      flutter build linux --release -v
      craftctl set version="$(jq -r '.version' build/flutter_assets/version.json)"
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
      sed -i -e 's|\(Icon=\).*|\1/bin/data/flutter_assets/data/media/ubuntu-accomplishments.svg|' \
          $CRAFT_PART_INSTALL/bin/data/flutter_assets/data/ubuntu-accomplishments.desktop

  community-accomplishments:
    plugin: nil
    source: https://github.com/UbuntuAccomplishments/community-accomplishments.git
    override-build: |
      ./install.sh $SNAPCRAFT_PART_INSTALL/usr/share/accomplishments
    stage:
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/general/attend-uds.accomplishment

  desktop-accomplishments:
    plugin: nil
    source: https://github.com/UbuntuAccomplishments/desktop-accomplishments.git
    override-build: |
      ./install.sh $SNAPCRAFT_PART_INSTALL/usr/share/accomplishments
    stage:
      # these still need porting or removing entirely
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/accessories/accomplishments-shared-with-validation-server.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/gaming/gnomine*.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/gaming/mahjongg*.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/gaming/sudoku*.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/general/installed-on-nexus7.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/multimedia/importshotwell.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/multimedia/multimedia-added-music.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/multimedia/multimedia-added-photos.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/multimedia/musicinrhythmbox.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/networking/gwibber-*.accomplishment
      - -usr/share/accomplishments/accomplishments/ubuntu-desktop/*/productivity/libreoffice-create-document.accomplishment

layout:
  /usr/share/libdrm/amdgpu.ids:
    symlink: $SNAP/gnome-platform/usr/share/libdrm/amdgpu.ids

slots:
  accomplishments-service:
    interface: dbus
    bus: session
    name: org.ubuntu.Accomplishments

plugs:
  accomplishments-viewer:
    interface: dbus
    bus: session
    name: org.ubuntu.Accomplishments
  etc-lsb-release:
    interface: system-files
    read:
      - /etc/lsb-release
  # gnomine-scores:
  #   interface: personal-files
  #   read:
  #     - $HOME/.local/share/gnome-mines/scores
  # mahjongg-scores:
  #   interface: system-files
  #   read:
  #     - $HOME/.local/share/gnome-mahjongg/history
  # sudoku-scores:
  #   interface: personal-files
  #   read:
  #     - $HOME/.local/share/gnome-sudoku/finished
  # missing rythmbox plug
  # missing shotwell plug

apps:
  daemon:
    command: bin/accomplishments-daemon
    daemon: simple
    passthrough:
      daemon-scope: user
    slots:
      - accomplishments-service # the dbus service
    plugs:
      - gsettings
      - hardware-observe
      - home
      - log-observe
      - network
      # our custom system access below:
      # - gnomine-scores
      # - mahjongg-scores
      # - sudoku-scores
      - etc-lsb-release

  ubuntu-accomplishments:
    command: bin/accomplishments_viewer
    common-id: org.ubuntu.Accomplishments
    desktop: bin/data/flutter_assets/data/ubuntu-accomplishments.desktop
    extensions: [gnome]
    plugs:
      - accomplishments-viewer # the dbus service
